<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADMINRG-5P4SOQB" ignored="0" name="Retry failed Test Cases" tests="9" failures="2" timestamp="22 Jul 2018 12:13:18 GMT" time="0.109" errors="0">
  <testcase name="Test" time="0.015" classname="mytests.MyTest"/>
  <testcase name="Test1" time="0.003" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.Test1(MyTest.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.003" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.004" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.Test2(MyTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Retry failed Test Cases -->
